version: '3'

services:
  todotests:
    build: ./todo-app/tests/
    restart: always
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    networks:
      - app
  
  todofront:
    build: ./todo-app/front-end/
    restart: always
    depends_on:
      - todoback
    ports:
      - "3000:3000"
    networks:
      - app

  todoback:
    build: ./todo-app/back-end/
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app
