version: '3'

services:
  todotests:
    image: ./tests/
    restart: always
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
  
  todofront:
    build: ./front-end/
    restart: always
    depends_on:
      - todoback
    ports:
      - "3000:3000"

  todoback:
    build: ./back-end/
    restart: always
    ports:
      - "3001:3001"
