version: '3'

services:
  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    restart: always
    environment:
      - FRONT_HOST=todofront
  
  todofront:
    image: todofront
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REACT_APP_API_HOST=todoback

  todoback:
    image: todoback
    ports:
      - "3001:3001"
